### ISSUE TITLE
Could not find hex value

### ISSUE THREAD

**Issue by 687958** [searayeah/dota-camera-distance#11] opened 2023-05-14 04:39 UTC
![screenshot_](https://github.com/searayeah/dota-camera-distance/assets/127166491/675278d6-9aa4-4460-99bb-ea3659f44e08)

Not sure if this is problem with patch 7.33c or only with me

**Comment by chatctha** [comment] 2023-05-14 06:12
I also encountered the same problem as you. It may be caused by patch 7.33c today.

**Comment by searayeah** [comment] 2023-05-14 06:48
Yep guys, I see. Fixing now

**Comment by webdevelopland** [comment] 2023-05-14 06:55
Same issue here. Thanks for fast check up @searayeah

**Comment by Dimk2** [comment] 2023-05-14 09:29
New HexValue: 00 C0 C1 44 00 00 C8 44 00 40 9C 45 00 C0 AC 45

**Comment by searayeah** [comment] 2023-05-14 09:42
Guys, it seems that I fixed it. Just relaunch the app(do not need to re-download). Everything should work now, report back if there are any problems.

Sorry for long fix, encountered some problems with Github.

**Comment by webdevelopland** [comment] 2023-05-14 11:33
@DmitryKing-DK 
```
00 00 96 44 00 00 C8 44 00 40 9C 45 00 C0 AC 45
```
This hex is wrong. It's found, but it doesn't change a camera distance in the game.

**Comment by webdevelopland** [comment] 2023-05-14 11:34
@searayeah 
```
00 00 96 44 00 00 C8 44
```
This hex is also wrong. Looks like there are hundrends of such blocks. I replaces fist 20, and even that didn't change the camera distance.

**Comment by searayeah** [comment] 2023-05-14 11:45
> @searayeah
> 
> ```
> 00 00 96 44 00 00 C8 44
> ```
> 
> This hex is also wrong. Looks like there are hundrends of such blocks. I replaced first 20, and even that didn't change the camera distance.

I think you might be doing something wrong here. Be sure that you are searching in ```\dota 2 beta\game\dota\bin\win64\client.dll``` and selecting ```hex-values``` in HxD search. For me -  I do not even have to use precise string that @DmitryKing-DK provided.
![image](https://github.com/searayeah/dota-camera-distance/assets/57370975/08022fbd-3b38-43b5-a888-011e9063582d)

It's enough to search for ```00 00 96 44 00 00 C8 44``` as it founds only one occurrence. The app uses the same strategy and I've tested it to work properly.

**Comment by webdevelopland** [comment] 2023-05-14 14:32
Cool, the last one works:  
```
00 00 AE 42 00 00 96 44 00 00 C8 44 00 40 9C 45
```
https://github.com/searayeah/dota-camera-distance/commit/cd90d8646d2754507e0f3422866363c09db377db

**Comment by searayeah** [comment] 2023-05-14 14:34
> Cool, the last one works:
> 
> ```
> 00 00 AE 42 00 00 96 44 00 00 C8 44 00 40 9C 45
> ```
> 
> [cd90d86](https://github.com/searayeah/dota-camera-distance/commit/cd90d8646d2754507e0f3422866363c09db377db)

Nice! If there are no other problems, I'm closing the issue

**Comment by webdevelopland** [comment] 2023-05-14 14:35
@searayeah Thank you!

**Closed by searayeah** 2023-05-14 14:34 UTC
